global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Python Producer metrics
  - job_name: 'python-producer'
    static_configs:
      - targets: ['python-producer:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node.js Consumer metrics
  - job_name: 'nodejs-consumer'
    static_configs:
      - targets: ['nodejs-consumer:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Kafka metrics (if JMX is enabled)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # MinIO metrics (if MinIO metrics are enabled)
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s
